# Generated by Django 5.1.15 on 2026-09-20 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Unique brand name of the restaurant (e.g., "Crunchy Bag")', max_length=150, unique=True, verbose_name='brand name')),
                ('slug', models.SlugField(help_text='URL-friendly unique slug for the brand', max_length=160, unique=True, verbose_name='brand slug')),
                ('pan_number', models.CharField(blank=True, default='', help_text='Official PAN or Tax Registration number for fiscal billing', max_length=30, verbose_name='PAN / VAT number')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='primary phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='brand contact email')),
                ('website', models.URLField(blank=True, default='', verbose_name='official website')),
                ('logo_url', models.URLField(blank=True, default='', verbose_name='brand logo URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='brand description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this restaurant brand is active and operating.', verbose_name='is active')),
                ('admin', models.ForeignKey(help_text='The primary restaurant owner/admin user responsible for this brand.', on_delete=django.db.models.deletion.PROTECT, related_name='administered_restaurants', to=settings.AUTH_USER_MODEL, verbose_name='restaurant admin / owner')),
            ],
            options={
                'verbose_name': 'restaurant brand',
                'verbose_name_plural': 'restaurant brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Outlet name, e.g., "Kathmandu Flagship", "Lalitpur Hub", "Airport Express"', max_length=150, verbose_name='outlet name')),
                ('branch_code', models.CharField(db_index=True, help_text='Unique operational code, e.g. "CB-KTM-001"', max_length=50, unique=True, verbose_name='branch code')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='outlet phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='outlet email')),
                ('address_line', models.CharField(blank=True, default='', max_length=255, verbose_name='street address')),
                ('city', models.CharField(default='Kathmandu', max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, default='Bagmati', max_length=100, verbose_name='state / province')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='postal code')),
                ('is_main_branch', models.BooleanField(default=False, help_text='Designates if this is the primary/flagship branch for the brand.', verbose_name='is main branch')),
                ('is_active', models.BooleanField(default=True, help_text='Master operational status for this outlet.', verbose_name='is active')),
                ('accepting_orders', models.BooleanField(default=True, help_text='Temporary toggle for kitchen overload or operational pauses.', verbose_name='accepting orders')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='branch manager')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurant', verbose_name='parent restaurant brand')),
            ],
            options={
                'verbose_name': 'branch outlet',
                'verbose_name_plural': 'branch outlets',
                'ordering': ['restaurant', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
    ]
