# Generated by Django 5.1.15 on 2026-09-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='enable_delivery',
            field=models.BooleanField(default=True, help_text='Allow delivery fulfillment from this outlet.', verbose_name='enable delivery'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enable_dine_in',
            field=models.BooleanField(default=True, help_text='Allow table seating and waiter service at this outlet.', verbose_name='enable dine-in'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enable_drive_thru',
            field=models.BooleanField(default=False, help_text='Allow vehicular drive-thru lane ordering.', verbose_name='enable drive-thru'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enable_kiosk',
            field=models.BooleanField(default=False, help_text='Enable self-ordering touch kiosks at this outlet.', verbose_name='enable self-order kiosk'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enable_pos',
            field=models.BooleanField(default=True, help_text='Enable cashier billing terminal at this outlet.', verbose_name='enable cashier POS'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enable_qr_ordering',
            field=models.BooleanField(default=True, help_text='Allow customers to scan table QR codes and place orders.', verbose_name='enable QR digital ordering'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enable_takeaway',
            field=models.BooleanField(default=True, help_text='Allow counter pick-up / takeaway orders.', verbose_name='enable takeaway'),
        ),
        migrations.AddField(
            model_name='branch',
            name='operate_type',
            field=models.CharField(choices=[('DINE_IN', 'Full Dine-In Restaurant'), ('EXPRESS_TAKEOUT', 'Express QSR / Takeaway'), ('CLOUD_KITCHEN', 'Cloud / Ghost Kitchen (Delivery Only)'), ('DRIVE_THRU', 'Drive-Thru & Pick-up'), ('FOOD_TRUCK_KIOSK', 'Food Truck / Kiosk'), ('HYBRID', 'Hybrid Multi-Channel Hub')], db_index=True, default='DINE_IN', help_text='Operating model for this outlet (Dine-in, Cloud Kitchen, Express Takeout, etc.)', max_length=30, verbose_name='operate type'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The assigned Outlet Administrator responsible for local operations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='outlet admin / manager'),
        ),
    ]
