# Generated by Django 5.1.15 on 2026-09-27 07:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_branch_enable_delivery_branch_enable_dine_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Registered address / Head office location', max_length=255, verbose_name='head office address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(default='NPR', help_text='Operational currency ISO code (e.g. NPR)', max_length=10, verbose_name='currency code'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency_symbol',
            field=models.CharField(default='रु', help_text='Currency symbol (e.g. रु or Rs.)', max_length=10, verbose_name='currency symbol'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='enable_card',
            field=models.BooleanField(default=True, help_text='Accept credit/debit card swipe POS terminal', verbose_name='enable card / POS swipe'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='enable_cash',
            field=models.BooleanField(default=True, help_text='Accept physical cash at cashier counter', verbose_name='enable cash payment'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='enable_esewa',
            field=models.BooleanField(default=True, help_text='Accept eSewa digital wallet QR and web checkout', verbose_name='enable eSewa wallet'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='enable_fonepay',
            field=models.BooleanField(default=True, help_text='Accept dynamic and static Fonepay QR network payments', verbose_name='enable Fonepay QR'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='enable_khalti',
            field=models.BooleanField(default=True, help_text='Accept Khalti digital wallet QR and web checkout', verbose_name='enable Khalti wallet'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fiscal_year',
            field=models.CharField(default='2081/82', help_text='Nepal Bikram Sambat fiscal accounting year (e.g. 2081/82)', max_length=20, verbose_name='current fiscal year'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ird_bill_prefix',
            field=models.CharField(default='CB-INV-', help_text='Prefix for statutory fiscal bills (e.g. "CB-INV-")', max_length=20, verbose_name='IRD invoice bill prefix'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ird_enable_realtime_sync',
            field=models.BooleanField(default=False, help_text='Flag to sync bills in real-time with IRD CBMS portal', verbose_name='enable IRD real-time sync'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ird_software_id',
            field=models.CharField(blank=True, default='', help_text='Registered CBMS IRD software registration ID', max_length=64, verbose_name='IRD software identifier'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_service_charge_enabled',
            field=models.BooleanField(default=False, help_text='Whether restaurant service charge is levied on dining orders', verbose_name='is service charge enabled'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_vat_enabled',
            field=models.BooleanField(default=True, help_text='Whether statutory VAT is charged on bills', verbose_name='is VAT enabled'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Official registered legal company name, e.g. "Crunchy Bag Food & Hospitality Pvt. Ltd."', max_length=200, verbose_name='registered legal entity name'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Uploaded brand logo image file', null=True, upload_to='organization/logos/', verbose_name='brand logo file'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hospitality service charge percentage (e.g. 0% or 10%)', max_digits=5, verbose_name='service charge (%)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Inland Revenue Department standard VAT rate (typically 13%)', max_digits=5, verbose_name='VAT rate (%)'),
        ),
    ]
