# Generated by Django 5.1.15 on 2026-09-24 03:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0002_branch_enable_delivery_branch_enable_dine_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Zone name (e.g. Core City 5km, Outer Ring Road)', max_length=120)),
                ('radius_km', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Service delivery radius in kilometers', max_digits=5)),
                ('center_lat', models.DecimalField(decimal_places=6, help_text='Latitude coordinate of branch / zone hub', max_digits=9)),
                ('center_lng', models.DecimalField(decimal_places=6, help_text='Longitude coordinate of branch / zone hub', max_digits=9)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Standard delivery fee in NPR', max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart subtotal required for delivery', max_digits=8)),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal above which delivery fee is waived', max_digits=8, null=True)),
                ('estimated_delivery_minutes', models.PositiveIntegerField(default=35, help_text='Estimated door-to-door delivery duration displayed to customers')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='restaurants.branch')),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'db_table': 'delivery_zone',
                'ordering': ['branch', 'radius_km'],
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('SCOOTER', 'Scooter'), ('BICYCLE', 'Bicycle'), ('ELECTRIC_EV', 'Electric EV'), ('CAR', 'Car / Van')], default='MOTORCYCLE', max_length=32)),
                ('vehicle_plate', models.CharField(help_text='Official vehicle registration / license plate number', max_length=32)),
                ('status', models.CharField(choices=[('OFFLINE', 'Offline'), ('AVAILABLE', 'Available for Orders'), ('BUSY', 'On Active Delivery')], db_index=True, default='OFFLINE', max_length=32)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(help_text='Primary hub / branch assignment', on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='restaurants.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Rider Profiles',
                'db_table': 'delivery_rider_profile',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_id', models.CharField(db_index=True, help_text='Unique dispatch reference (e.g. DSP-260924-0001)', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Waiting for Rider Assignment'), ('ASSIGNED', 'Rider Assigned'), ('ACCEPTED', 'Rider Accepted Order'), ('PICKED_UP', 'Picked Up from Kitchen (Out for Delivery)'), ('ARRIVED', 'Arrived at Customer Location'), ('DELIVERED', 'Delivered & Handed Over'), ('FAILED', 'Delivery Failed / Customer Unreachable')], db_index=True, default='UNASSIGNED', max_length=32)),
                ('delivery_address', models.TextField(help_text='Destination address provided by customer')),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rider_notes', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='restaurants.branch')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_dispatch', to='orders.order')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='delivery.deliveryzone')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to='delivery.riderprofile')),
            ],
            options={
                'verbose_name': 'Delivery Dispatch',
                'verbose_name_plural': 'Delivery Dispatches',
                'db_table': 'delivery_dispatch',
                'ordering': ['-created_at'],
            },
        ),
    ]
