# Generated by Django 5.1.15 on 2026-09-22 18:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('restaurants', '0002_branch_enable_delivery_branch_enable_dine_in_and_more'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, help_text='Human-readable unique order code (e.g. CB-KTM-260922-0001)', max_length=64, unique=True)),
                ('table_session_id', models.UUIDField(blank=True, db_index=True, help_text='Active dining tab session grouping multiple order rounds', null=True)),
                ('customer_name', models.CharField(default='Guest', max_length=120)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('fulfillment_type', models.CharField(choices=[('DINE_IN', 'Dine-In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery'), ('DRIVE_THRU', 'Drive-Thru')], db_index=True, default='DINE_IN', max_length=32)),
                ('order_source', models.CharField(choices=[('TABLE_QR', 'Table QR Digital Menu'), ('KIOSK', 'Self-Service Kiosk'), ('POS', 'Cashier POS'), ('WEBSITE', 'Customer Web Ordering')], db_index=True, default='TABLE_QR', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('ACCEPTED', 'Accepted by Kitchen'), ('PREPARING', 'In Kitchen Preparation'), ('READY', 'Ready for Serving / Pickup'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed & Settled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card Payment'), ('ESEWA', 'eSewa Digital Wallet'), ('KHALTI', 'Khalti Digital Wallet'), ('FONEPAY', 'Fonepay QR'), ('PAY_AT_COUNTER', 'Pay at Cashier Counter')], default='CASH', max_length=32)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], db_index=True, default='UNPAID', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_included_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Statutory 13% tax-inclusive VAT portion included in subtotal', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_round_down_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Statutory cash currency round-down savings (subtotal - floor(subtotal))', max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes and system tags')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.branch')),
                ('table', models.ForeignKey(blank=True, help_text='Assigned table for DINE_IN orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tables.diningtable')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(help_text='Historical name snapshot', max_length=200)),
                ('variant_name', models.CharField(blank=True, default='', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_kitchen', models.BooleanField(db_index=True, default=True, help_text='Rule 2: If False, bypasses KDS preparation ticket (e.g. retail canned drinks)')),
                ('round_number', models.PositiveSmallIntegerField(default=1, help_text='Table round indicator for active dining sessions')),
                ('item_notes', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'orders_order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=120)),
                ('option_name', models.CharField(max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Order Item Modifier',
                'verbose_name_plural': 'Order Item Modifiers',
                'db_table': 'orders_item_modifier',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'db_table': 'orders_status_history',
                'ordering': ['created_at'],
            },
        ),
    ]
