# Generated by Django 5.1.15 on 2026-09-23 17:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0002_branch_enable_delivery_branch_enable_dine_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Sequential official tax receipt number (e.g. INV-CB-KTM-000123)', max_length=64, unique=True)),
                ('fiscal_year', models.CharField(default='2081/82', help_text='Fiscal accounting year', max_length=32)),
                ('seller_pan', models.CharField(help_text='Statutory PAN Number of restaurant brand', max_length=32)),
                ('customer_name', models.CharField(default='Guest', max_length=120)),
                ('customer_pan', models.CharField(blank=True, default='', help_text='Optional customer PAN for corporate / B2B expense invoices', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, help_text='13% statutory tax portion', max_digits=12)),
                ('cash_round_down_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=32)),
                ('is_synced_ird', models.BooleanField(default=False, help_text='Flag indicating synchronization with Inland Revenue Department e-billing API')),
                ('printed_count', models.PositiveIntegerField(default=1, help_text='Number of times physical thermal receipt has been printed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_invoices', to='restaurants.branch')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_invoice', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_invoices', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Fiscal Tax Invoice',
                'verbose_name_plural': 'Fiscal Tax Invoices',
                'db_table': 'payments_fiscal_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction reference (e.g. TXN-260923-0001)', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=32)),
                ('gateway_ref', models.CharField(blank=True, default='', help_text='Reference token or transaction ID from payment gateway (Fonepay, eSewa, Khalti)', max_length=128)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw payload returned from gateway webhook or terminal')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client idempotency key preventing duplicate payment processing', max_length=128, null=True, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='restaurants.branch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('received_by', models.ForeignKey(blank=True, help_text='Cashier or staff who collected counter payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payments_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
