# Generated by Django 5.1.15 on 2026-09-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_branch_enable_delivery_branch_enable_dine_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.CharField(db_index=True, help_text='Human readable table label (e.g. T-01, Booth 4, Patio 2)', max_length=32)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('section', models.CharField(default='Main Hall', help_text='Physical zone (e.g. Main Hall, Terrace, Rooftop, Bar)', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle table active or under maintenance')),
                ('qr_token_salt', models.CharField(blank=True, default='', help_text='Unique table salt for cryptographic opaque QR token generation', max_length=32)),
                ('active_session_id', models.UUIDField(blank=True, help_text='UUID of active running dining tab session', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_tables', to='restaurants.branch')),
            ],
            options={
                'verbose_name': 'Dining Table',
                'verbose_name_plural': 'Dining Tables',
                'db_table': 'dining_table',
                'ordering': ['branch', 'table_number'],
                'unique_together': {('branch', 'table_number')},
            },
        ),
    ]
