# Generated by Django 5.1.15 on 2026-09-23 17:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0002_branch_enable_delivery_branch_enable_dine_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
                'db_table': 'inventory_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit (e.g. SKU-BUN-BRIOCHE, SKU-CAN-COKE-330)', max_length=64)),
                ('name', models.CharField(db_index=True, help_text='Item name (e.g. Brioche Bun, Beef Patty 150g, Canned Cola)', max_length=150)),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Current available quantity in stock', max_digits=12)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces (Count)'), ('KG', 'Kilograms (kg)'), ('GRAMS', 'Grams (g)'), ('LITERS', 'Liters (L)'), ('MILLILITERS', 'Milliliters (ml)'), ('PACKS', 'Packs')], default='PCS', max_length=32)),
                ('min_threshold', models.DecimalField(decimal_places=3, default=Decimal('5.000'), help_text='Threshold below which low-stock alert triggers', max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Purchase unit cost in NPR', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='restaurants.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_item',
                'ordering': ['branch', 'name'],
                'unique_together': {('branch', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity of raw inventory item consumed per menu portion', max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='inventory.inventoryitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, help_text='If set, ingredient applies specifically to this variant (e.g. Double Patty)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'db_table': 'inventory_recipe_item',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ORDER_DEDUCTION', 'Order Deduction'), ('RESTOCK_PURCHASE', 'Restock / Purchase'), ('WASTAGE_SPOILAGE', 'Wastage / Spoilage'), ('AUDIT_ADJUSTMENT', 'Audit Adjustment')], db_index=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive for additions/restock, negative for order consumption/wastage', max_digits=12)),
                ('previous_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('resulting_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_deductions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'inventory_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
