# Generated by Django 5.1.15 on 2026-09-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Stock Transaction', 'verbose_name_plural': 'Stock Transactions'},
        ),
    ]
