# Generated by Django 5.1.15 on 2026-09-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_user_branch_user_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrator'), ('RESTAURANT_OWNER', 'Restaurant Owner'), ('BRANCH_MANAGER', 'Branch Manager'), ('CHEF', 'Kitchen Chef'), ('WAITER', 'Waiter / Server'), ('CASHIER', 'Cashier / Billing'), ('RIDER', 'Delivery Rider'), ('CUSTOMER', 'Customer')], db_index=True, default='CUSTOMER', max_length=30, verbose_name='user role'),
        ),
    ]
