# Generated by Django 5.1.15 on 2026-09-25 10:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_branch_enable_delivery_branch_enable_dine_in_and_more'),
        ('user_accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('STORE_MANAGER', 'Store Manager'), ('CASHIER', 'Cashier'), ('KITCHEN_SUPERVISOR', 'Kitchen Supervisor'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('FLOOR_STAFF', 'Floor Staff')], db_index=True, default='CASHIER', max_length=32)),
                ('title', models.CharField(blank=True, default='', help_text='e.g. Head Cashier & Shift Lead', max_length=120)),
                ('salary_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base monthly salary in NPR', max_digits=12)),
                ('assigned_pages', models.JSONField(default=list, help_text="List of AdminSubPage keys: ['pos', 'daybook', 'loyalty']")),
                ('pin_hash', models.CharField(blank=True, help_text='Hashed 4-to-6 digit quick POS terminal switch PIN', max_length=128, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('assigned_outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='restaurants.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee profile',
                'verbose_name_plural': 'employee profiles',
                'db_table': 'user_accounts_employee',
                'ordering': ['-created_at'],
            },
        ),
    ]
