# Generated by Django 5.1.15 on 2026-09-25 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
