# Generated by Django 5.1.15 on 2026-09-22 17:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_branch_enable_delivery_branch_enable_dine_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('icon_name', models.CharField(default='Utensils', help_text='Lucide icon identifier', max_length=64)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('hsn_code', models.CharField(blank=True, default='', help_text='Statutory HSN/SAC code', max_length=16)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'catalog_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('min_selections', models.PositiveSmallIntegerField(default=0)),
                ('max_selections', models.PositiveSmallIntegerField(default=1, help_text='If 1, acts as radio single-select; if > 1, acts as multi-select checkbox')),
                ('required', models.BooleanField(default=False, help_text='If True, at least min_selections (>= 1) is required before adding to cart')),
            ],
            options={
                'verbose_name': 'Modifier Group',
                'verbose_name_plural': 'Modifier Groups',
                'db_table': 'catalog_modifier_group',
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional surcharge in NPR (0.00 for free choice)', max_digits=8)),
                ('is_default', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.modifiergroup')),
            ],
            options={
                'verbose_name': 'Modifier Option',
                'verbose_name_plural': 'Modifier Options',
                'db_table': 'catalog_modifier_option',
                'ordering': ['price_delta', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OutletTimePricingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.JSONField(default=list, help_text="List of days: ['Mon', 'Tue', ...]")),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('product_ids', models.JSONField(blank=True, default=list, help_text='List of prod-* IDs targeted')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_schedules', to='restaurants.branch')),
            ],
            options={
                'verbose_name': 'Outlet Time Pricing Schedule',
                'verbose_name_plural': 'Outlet Time Pricing Schedules',
                'db_table': 'outlet_time_pricing_schedule',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base retail price in NPR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='COGS for margin tracking (defaults to ~45% of base price if omitted)', max_digits=10, null=True)),
                ('prep_time_minutes', models.PositiveIntegerField(default=12, help_text='Estimated kitchen prep time displayed on product cards & KDS')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Caloric energy count (kcal)', null=True)),
                ('dietary_tags', models.JSONField(blank=True, default=list, help_text="Array: Halal, Spicy, Vegetarian, Chef's Choice, Popular")),
                ('images', models.JSONField(blank=True, default=list, help_text='Array of image URLs (string[])')),
                ('main_image_index', models.PositiveSmallIntegerField(default=0, help_text='Index into images array for primary thumbnail')),
                ('is_delivery_eligible', models.BooleanField(db_index=True, default=True)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Master availability toggle')),
                ('is_web_visible', models.BooleanField(db_index=True, default=True)),
                ('show_on_pos', models.BooleanField(db_index=True, default=True)),
                ('show_on_qr', models.BooleanField(db_index=True, default=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('requires_kitchen', models.BooleanField(db_index=True, default=True, help_text='If False, bypasses KDS prep ticket (e.g. canned drinks, cigarettes)')),
                ('is_counter_direct', models.BooleanField(default=False, help_text='Sold directly across counter')),
                ('is_direct_inventory_item', models.BooleanField(default=False, help_text='Sold 1:1 directly from stock inventory')),
                ('is_combo_package', models.BooleanField(db_index=True, default=False)),
                ('combo_discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_price', 'Fixed Price'), ('amount_off', 'Amount Off')], max_length=20, null=True)),
                ('combo_discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('combo_original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated sum of individual items before bundle discount', max_digits=10, null=True)),
                ('combo_items', models.JSONField(blank=True, default=list, help_text='Array of bundled items: [{product_id, quantity, is_default, allow_substitution}]')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'catalog_product',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='catalog.product'),
        ),
        migrations.CreateModel(
            name='ProductTimePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(default='All Days', help_text="e.g. 'All Days' or 'Mon-Fri'", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_pricings', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Time Pricing',
                'verbose_name_plural': 'Product Time Pricings',
                'db_table': 'catalog_product_time_pricing',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Absolute variant price overriding product base price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'catalog_product_variant',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='OutletProductOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Outlet-specific stock toggle (False = Sold Out at this branch)')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Outlet-specific price override (null uses global catalog price)', max_digits=10, null=True)),
                ('is_web_visible', models.BooleanField(blank=True, null=True)),
                ('show_on_pos', models.BooleanField(blank=True, null=True)),
                ('show_on_qr', models.BooleanField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_overrides', to='restaurants.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_overrides', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Outlet Product Override',
                'verbose_name_plural': 'Outlet Product Overrides',
                'db_table': 'outlet_product_override',
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
